# Generated by Django 2.1.4 on 2019-09-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitionapproval',
            old_name='skip',
            new_name='skipped',
        ),
        migrations.AddField(
            model_name='transitionapproval',
            name='skipped_from',
            field=models.ManyToManyField(blank=True, null=True, related_name='_transitionapproval_skipped_from_+', to='river.TransitionApproval', verbose_name='Skipped from'),
        ),
    ]
